# Sampling origins across different cities and creating origin-destination pairs.

## Prerequisites
This repository builds on the python package OSMNx (v.2.0.1, https://osmnx.readthedocs.io/en/stable/). I recommend installing it via conda:
```
conda create -n ox -c conda-forge --strict-channel-priority osmnx
```
For sampling nodes based on city names two additional packages are required, namely geopy (v.2.3.1, https://geopy.readthedocs.io/en/stable/) and overpy (v.0.7, https://python-overpy.readthedocs.io/en/latest/)

```
pip install geopy
pip install overpy nodes run Ubuntu Jammy 22.04 LTS.
There is local scratch space on each node, which is shared between the jobs currently running. Connected to Kebnekaise is also our parallel file system Ransarn (where your project storage is located), which provide quick access to files regardless of which node they run on. For more information about the different file systems that are available on our systems, read the Filesystems and Storage page.
```

For visualizing routes and geometry on maps I use the folium package (v.0.19.4, https://python-visualization.github.io/folium/latest/) that is included in the OSMNx package, but for creating static images of these visualizations the Selenium package is required (v.4.28.0, https://www.selenium.dev/documentation/)

```
pip install selenium
```

## This exampleCities are used as the basis to find random samples of intersections. The region and country names are nice to have, but they are not necessary.

In [1]:
# region <set up parameters>

import os
import csv
import pandas as pd
import multiprocessing

from datetime import datetime
sample_size = 5
min_distance = 2
random_seed = 4
network_type = 'drive'
point_distance_size = 10000
experiment_name = "2025-11-illustration"
#base_path=f"/proj/nobackup/streetnetwork-alignment/{experiment_name}" for HPC2N
base_path=f"/media/arvidkh/projekt/streetnetwork-alignment/{experiment_name}"
min_od_distance = 4750
max_od_distance = 5250
od_pair_sample_size = 180


if not os.path.exists(base_path):
    os.makedirs(base_path)

parameters_file_path = os.path.join(base_path, f"parameters_2025_12_01.csv")
city_sample_nodes_path = os.path.join(base_path, f'city_sample_nodes_{experiment_name}.csv')
local_graph_folder = os.path.join(base_path, 'local_origin_graphs')

with open(parameters_file_path, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["Parameter", "Value"])
    writer.writerow(["sample_size", sample_size])
    writer.writerow(["min_distance", min_distance])
    writer.writerow(["random_seed", random_seed])
    writer.writerow(["network_type", network_type])
    writer.writerow(["point_distance_size", point_distance_size])
    writer.writerow(["min_od_distance", min_od_distance])
    writer.writerow(["max_od_distance", max_od_distance])
    writer.writerow(["base_path", base_path])
    writer.writerow(["city_sample_nodes_path", city_sample_nodes_path])
    writer.writerow(["local_graph_folder", local_graph_folder])
    writer.writerow(["base_path", base_path])
    writer.writerow(["experiment_name", experiment_name])


param = pd.read_csv(parameters_file_path)
display(param)



num_processes = multiprocessing.cpu_count()  # Adjust based on your system's capabilities
print(f"Number of processes to use: {num_processes}")

# endregion

                 Parameter                                              Value
0              sample_size                                                  5
1             min_distance                                                  2
2              random_seed                                                  4
3             network_type                                              drive
4      point_distance_size                                              10000
5          min_od_distance                                               4750
6          max_od_distance                                               5250
7                base_path  /media/arvidkh/projekt/streetnetwork-alignment...
8   city_sample_nodes_path  /media/arvidkh/projekt/streetnetwork-alignment...
9       local_graph_folder  /media/arvidkh/projekt/streetnetwork-alignment...
10               base_path  /media/arvidkh/projekt/streetnetwork-alignment...
11         experiment_name                               2025-11-illustration

Number of processes to use: 8

In [2]:
# region <get node sample from cities>
# The workflow for analyzing the routes begins with coordinate points used as origin locations.
import os 
import pandas as pd
from route_network_analysis import node_sampling
df = pd.read_csv("16_city_sample.csv")

city_sample_nodes_path = os.path.join(base_path, f'city_sample_nodes_{experiment_name}.csv')

if os.path.exists(city_sample_nodes_path):
    print("sample nodes already retrieved")
else:
    node_sample_df = node_sampling.get_random_nodes_for_all_cities(df, min_distance_km=min_distance, sample_size=sample_size,random_seed=random_seed)
    node_sample_df['graph_path'] = node_sample_df.apply(lambda row: os.path.join(local_graph_folder, f"{row['city_name_en']}_{row['node_id']}.graphml"), axis=1)
    node_sample_df.to_csv(os.path.join(base_path, city_sample_nodes_path))

# endregion

Random nodes for Lima that are at least 2 km apart: [1330495156, 1359116964, 848394908, 11050450864, 3107812023]
Random nodes for Lima: [1330495156, 1359116964, 848394908, 11050450864, 3107812023]
Node: 1330495156
Random node coordinates for Lima: -11.9789855, -77.0547884
Node: 1359116964
Random node coordinates for Lima: -12.0097364, -77.0931582
Node: 848394908
Random node coordinates for Lima: -12.0276739, -77.0958306
Node: 11050450864
Random node coordinates for Lima: -11.9433227, -77.0076102
Node: 3107812023
Random node coordinates for Lima: -11.8927561, -76.9439907
Random nodes for Buenos Aires that are at least 2 km apart: [1406097496, 1422501545, 1357237840, 5533758329, 9852258020]
Random nodes for Buenos Aires: [1406097496, 1422501545, 1357237840, 5533758329, 9852258020]
Node: 1406097496
Random node coordinates for Buenos Aires: -33.3550713, -60.2680864
Node: 1422501545
Random node coordinates for Buenos Aires: -33.2935262, -60.2644707
Node: 1357237840
Random node coordinates for Buenos Aires: -33.3525285, -60.2226833
Node: 5533758329
Random node coordinates for Buenos Aires: -33.3843326, -60.2707887
Node: 9852258020
Random node coordinates for Buenos Aires: -33.4316899, -60.1398797
Random nodes for Mexico City that are at least 2 km apart: [506391266, 762649538, 280151390, 7951676238, 2335775204]
Random nodes for Mexico City: [506391266, 762649538, 280151390, 7951676238, 2335775204]
Node: 506391266
Random node coordinates for Mexico City: 19.304158, -99.0704394
Node: 762649538
Random node coordinates for Mexico City: 19.2902209, -99.1145616
Node: 280151390
Random node coordinates for Mexico City: 19.3052581, -99.1861932
Node: 7951676238
Random node coordinates for Mexico City: 19.3367985, -99.2329932
Node: 2335775204
Random node coordinates for Mexico City: 19.3784173, -99.2307695
Random nodes for Miami that are at least 2 km apart: [99232717, 99343234, 99119377, 3505119075, 8073291354]
Random nodes for Miami: [99232717, 99343234, 99119377, 3505119075, 8073291354]
Node: 99232717
Random node coordinates for Miami: 25.7600742, -80.2142515
Node: 99343234
Random node coordinates for Miami: 25.837137, -80.22717
Node: 99119377
Random node coordinates for Miami: 25.8132467, -80.2260662
Node: 3505119075
Random node coordinates for Miami: 25.8077014, -80.1952845
Node: 8073291354
Random node coordinates for Miami: 25.7440263, -80.2338282
Random nodes for Pittsburgh that are at least 2 km apart: [105097688, 105719059, 104716142, 106075671, 1027077885]
Random nodes for Pittsburgh: [105097688, 105719059, 104716142, 106075671, 1027077885]
Node: 105097688
Random node coordinates for Pittsburgh: 40.4472996, -79.9441699
Node: 105719059
Random node coordinates for Pittsburgh: 40.5029126, -80.0691119
Node: 104716142
Random node coordinates for Pittsburgh: 40.4333254, -79.8773441
Node: 106075671
Random node coordinates for Pittsburgh: 40.5029372, -79.9605845
Node: 1027077885
Random node coordinates for Pittsburgh: 40.3953484, -80.0412715
Random nodes for Seattle that are at least 2 km apart: [53199898, 59594019, 53113626, 4607144987, 9179103065]
Random nodes for Seattle: [53199898, 59594019, 53113626, 4607144987, 9179103065]
Node: 53199898
Random node coordinates for Seattle: 47.6927889, -122.1979787
Node: 59594019
Random node coordinates for Seattle: 47.6562824, -122.3178714
Node: 53113626
Random node coordinates for Seattle: 47.5419238, -122.2914466
Node: 4607144987
Random node coordinates for Seattle: 47.6300043, -122.3690177
Node: 9179103065
Random node coordinates for Seattle: 47.6170486, -122.303549
Random nodes for Rome that are at least 2 km apart: [298573501, 302024499, 259041554, 5368981033, 307509211]
Random nodes for Rome: [298573501, 302024499, 259041554, 5368981033, 307509211]
Node: 298573501
Random node coordinates for Rome: 41.8200434, 12.4705696
Node: 302024499
Random node coordinates for Rome: 41.8697544, 12.5679299
Node: 259041554
Random node coordinates for Rome: 41.925528, 12.5157613
Node: 5368981033
Random node coordinates for Rome: 41.8520241, 12.4554731
Node: 307509211
Random node coordinates for Rome: 41.8230841, 12.413846
Random nodes for Barcelona that are at least 2 km apart: [600061492, 1017920257, 269381939, 1883289262, 4111508831]
Random nodes for Barcelona: [600061492, 1017920257, 269381939, 1883289262, 4111508831]
Node: 600061492
Random node coordinates for Barcelona: 41.4434502, 2.2054524
Node: 1017920257
Random node coordinates for Barcelona: 41.4302881, 2.177365
Node: 269381939
Random node coordinates for Barcelona: 41.394126, 2.1421316
Node: 1883289262
Random node coordinates for Barcelona: 41.3568752, 2.0664523
Node: 4111508831
Random node coordinates for Barcelona: 41.3290349, 2.134329
Random nodes for Stockholm that are at least 2 km apart: [299803577, 447281012, 34032590, 1251168984, 1976750065]
Random nodes for Stockholm: [299803577, 447281012, 34032590, 1251168984, 1976750065]
Node: 299803577
Random node coordinates for Stockholm: 59.2391246, 18.0090384
Node: 447281012
Random node coordinates for Stockholm: 59.3360098, 18.061985
Node: 34032590
Random node coordinates for Stockholm: 59.3557349, 18.164352
Node: 1251168984
Random node coordinates for Stockholm: 59.3081345, 18.0260495
Node: 1976750065
Random node coordinates for Stockholm: 59.3707656, 17.9992645
Random nodes for Tehran that are at least 2 km apart: [2090004410, 3844939727, 1292514023, 4640003489, 5243833774]
Random nodes for Tehran: [2090004410, 3844939727, 1292514023, 4640003489, 5243833774]
Node: 2090004410
Random node coordinates for Tehran: 35.6614965, 51.4330345
Node: 3844939727
Random node coordinates for Tehran: 35.773317, 51.370096
Node: 1292514023
Random node coordinates for Tehran: 35.6316965, 51.3856835
Node: 4640003489
Random node coordinates for Tehran: 35.7056184, 51.4385992
Node: 5243833774
Random node coordinates for Tehran: 35.6673385, 51.4061711
Random nodes for Istanbul that are at least 2 km apart: [1058892495, 1134770756, 775654779, 12162557816, 2261051761]
Random nodes for Istanbul: [1058892495, 1134770756, 775654779, 12162557816, 2261051761]
Node: 1058892495
Random node coordinates for Istanbul: 41.007157, 28.9493074
Node: 1134770756
Random node coordinates for Istanbul: 41.0941909, 28.8709626
Node: 775654779
Random node coordinates for Istanbul: 41.083461, 29.0201039
Node: 12162557816
Random node coordinates for Istanbul: 41.0052245, 29.0942298
Node: 2261051761
Random node coordinates for Istanbul: 41.0719889, 28.9428326
Random nodes for Mogadishu that are at least 2 km apart: [1412578845, 2429173550, 317671002, 12726434014, 5636439912]
Random nodes for Mogadishu: [1412578845, 2429173550, 317671002, 12726434014, 5636439912]
Node: 1412578845
Random node coordinates for Mogadishu: 2.0724522, 45.3167358
Node: 2429173550
Random node coordinates for Mogadishu: 2.0515507, 45.3172759
Node: 317671002
Random node coordinates for Mogadishu: 2.0170263, 45.2912428
Node: 12726434014
Random node coordinates for Mogadishu: 2.0466139, 45.366536
Node: 5636439912
Random node coordinates for Mogadishu: 2.0968747, 45.3415134
Random nodes for Bangkok that are at least 2 km apart: [2629986341, 3825321129, 1687458454, 7936842527, 4822918883]
Random nodes for Bangkok: [2629986341, 3825321129, 1687458454, 7936842527, 4822918883]
Node: 2629986341
Random node coordinates for Bangkok: 13.7241695, 100.5218487
Node: 3825321129
Random node coordinates for Bangkok: 13.7249109, 100.4609744
Node: 1687458454
Random node coordinates for Bangkok: 13.7938157, 100.5681935
Node: 7936842527
Random node coordinates for Bangkok: 13.6695692, 100.4307363
Node: 4822918883
Random node coordinates for Bangkok: 13.7924541, 100.4458265
Random nodes for Melbourne that are at least 2 km apart: [319642519, 683089001, 247492201, 3353364995, 9976415226]
Random nodes for Melbourne: [319642519, 683089001, 247492201, 3353364995, 9976415226]
Node: 319642519
Random node coordinates for Melbourne: -37.8394336, 144.8551253
Node: 683089001
Random node coordinates for Melbourne: -37.8290585, 144.920253
Node: 247492201
Random node coordinates for Melbourne: -37.8810154, 145.0238564
Node: 3353364995
Random node coordinates for Melbourne: -37.8308555, 144.9650519
Node: 9976415226
Random node coordinates for Melbourne: -37.8923018, 144.9954526
Random nodes for Shanghai that are at least 2 km apart: [622623197, 838507201, 475861592, 11751956757, 1803562530]
Random nodes for Shanghai: [622623197, 838507201, 475861592, 11751956757, 1803562530]
Node: 622623197
Random node coordinates for Shanghai: 31.2047956, 121.4662599
Node: 838507201
Random node coordinates for Shanghai: 31.1842744, 121.3899739
Node: 475861592
Random node coordinates for Shanghai: 31.2502287, 121.4892488
Node: 11751956757
Random node coordinates for Shanghai: 31.21574, 121.3964503
Node: 1803562530
Random node coordinates for Shanghai: 31.2181653, 121.5274726

In [3]:
# region <create graphs>
import os  # for file operations
import pandas as pd  # for reading the csv file
import joblib
import logging
import ast
import route_network_analysis as rna
import osmnx as ox
logging.basicConfig(level=logging.ERROR, format='%(asctime)s - %(levelname)s - %(message)s',filename='jupyter.log', filemode='w')

#
sub_folder = "local_origin_graphs"
local_graph_folder = os.path.join(base_path, sub_folder)
if not os.path.exists(local_graph_folder):
    os.makedirs(local_graph_folder)

print(city_sample_nodes_path)
df = pd.read_csv(city_sample_nodes_path)
print(df['graph_path'])
def create_graphs(row):
    if os.path.exists(row['graph_path']):
        print(f"Graph exists: {row['graph_path']}")
        return True, row['city_name'], row['node_id']
    else:
        print(f"---Graph missing: {row['graph_path']}---")
        # Apply the function asynchronously
    try:
        latlon_point = ast.literal_eval(row['node_latlon'])
        og = rna.origin_graph(origin_point=latlon_point, distance_from_point=point_distance_size,
                          city_name=row["city_name_en"], network_type=network_type, remove_parallel=True, simplify=True)
    
        og.save_graph(row['graph_path'])
    
        # Plot the origin graph to see if something is obviously wrong
        ox.plot_graph(og.graph, node_color='blue', node_size=5, edge_linewidth=1, edge_color='black', bgcolor='white',
                       save=True, filepath=os.path.join(local_graph_folder, f"{row['city_name']}_{row['node_id']}.png"), show=False)
        logging.error(f"Finished with graph: {row['graph_path']}")
        return True, row['city_name'], row['node_id']

    except Exception as e:
        logging.error(f"error {e} creating {row['graph_path']}")
        return False, row['city_name'], row['node_id'], e
        

# Number of processes to use
num_processes = (joblib.cpu_count()-2)
print(f"Number of processes to use: {num_processes}")

# Collect results from joblib
results = []
try:

    results = joblib.Parallel(n_jobs=num_processes,backend='loky')(
        joblib.delayed(create_graphs)(row) for _, row in df.iterrows()
    )
except Exception as e:
    print(f"Joblib parallel processing error: {e}")
    
for result in results:
    if not result[0]: 
        print(f"failed creating graph {result[1]}{result[2]}. error {result[3]}")
    else:
        print(f"finished creating graph {result[1]}{result[2]}")

print("finished")

# endregion

/media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/city_sample_nodes_2025-11-illustration.csv
0     /media/arvidkh/projekt/streetnetwork-alignment...
1     /media/arvidkh/projekt/streetnetwork-alignment...
2     /media/arvidkh/projekt/streetnetwork-alignment...
3     /media/arvidkh/projekt/streetnetwork-alignment...
4     /media/arvidkh/projekt/streetnetwork-alignment...
                            ...
70    /media/arvidkh/projekt/streetnetwork-alignment...
71    /media/arvidkh/projekt/streetnetwork-alignment...
72    /media/arvidkh/projekt/streetnetwork-alignment...
73    /media/arvidkh/projekt/streetnetwork-alignment...
74    /media/arvidkh/projekt/streetnetwork-alignment...
Name: graph_path, Length: 75, dtype: object
Number of processes to use: 6
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Lima_1330495156.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Buenos Aires_1422501545.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Buenos Aires_1357237840.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Buenos Aires_5533758329.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Buenos Aires_9852258020.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Mexico City_506391266.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Mexico City_762649538.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Mexico City_280151390.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Mexico City_7951676238.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Mexico City_2335775204.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Miami_99232717.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Miami_99343234.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Miami_99119377.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Miami_3505119075.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Miami_8073291354.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Pittsburgh_105097688.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Pittsburgh_105719059.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Pittsburgh_104716142.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Pittsburgh_106075671.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Pittsburgh_1027077885.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Seattle_53199898.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Seattle_59594019.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Seattle_53113626.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Seattle_4607144987.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Seattle_9179103065.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Rome_298573501.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Rome_302024499.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Rome_259041554.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Rome_5368981033.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Rome_307509211.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Barcelona_600061492.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Barcelona_1017920257.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Barcelona_269381939.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Barcelona_1883289262.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Barcelona_4111508831.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Stockholm_299803577.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Stockholm_447281012.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Stockholm_34032590.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Stockholm_1251168984.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Stockholm_1976750065.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Tehran_2090004410.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Tehran_3844939727.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Tehran_1292514023.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Tehran_4640003489.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Tehran_5243833774.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Istanbul_1058892495.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Istanbul_1134770756.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Istanbul_775654779.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Istanbul_12162557816.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Istanbul_2261051761.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Mogadishu_1412578845.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Mogadishu_2429173550.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Mogadishu_317671002.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Mogadishu_12726434014.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Mogadishu_5636439912.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Bangkok_2629986341.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Bangkok_3825321129.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Bangkok_1687458454.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Bangkok_7936842527.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Bangkok_4822918883.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Melbourne_319642519.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Melbourne_683089001.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Melbourne_247492201.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Melbourne_3353364995.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Melbourne_9976415226.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Shanghai_622623197.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Shanghai_838507201.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Shanghai_475861592.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Shanghai_11751956757.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Shanghai_1803562530.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Buenos Aires_1406097496.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Lima_1359116964.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Lima_3107812023.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Lima_848394908.graphml
Graph exists: /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/local_origin_graphs/Lima_11050450864.graphml
finished creating graph Lima1330495156
finished creating graph Lima1359116964
finished creating graph Lima848394908
finished creating graph Lima11050450864
finished creating graph Lima3107812023
finished creating graph Buenos Aires1406097496
finished creating graph Buenos Aires1422501545
finished creating graph Buenos Aires1357237840
finished creating graph Buenos Aires5533758329
finished creating graph Buenos Aires9852258020
finished creating graph Mexico City506391266
finished creating graph Mexico City762649538
finished creating graph Mexico City280151390
finished creating graph Mexico City7951676238
finished creating graph Mexico City2335775204
finished creating graph Miami99232717
finished creating graph Miami99343234
finished creating graph Miami99119377
finished creating graph Miami3505119075
finished creating graph Miami8073291354
finished creating graph Pittsburgh105097688
finished creating graph Pittsburgh105719059
finished creating graph Pittsburgh104716142
finished creating graph Pittsburgh106075671
finished creating graph Pittsburgh1027077885
finished creating graph Seattle53199898
finished creating graph Seattle59594019
finished creating graph Seattle53113626
finished creating graph Seattle4607144987
finished creating graph Seattle9179103065
finished creating graph Rome298573501
finished creating graph Rome302024499
finished creating graph Rome259041554
finished creating graph Rome5368981033
finished creating graph Rome307509211
finished creating graph Barcelona600061492
finished creating graph Barcelona1017920257
finished creating graph Barcelona269381939
finished creating graph Barcelona1883289262
finished creating graph Barcelona4111508831
finished creating graph Stockholm299803577
finished creating graph Stockholm447281012
finished creating graph Stockholm34032590
finished creating graph Stockholm1251168984
finished creating graph Stockholm1976750065
finished creating graph Tehran2090004410
finished creating graph Tehran3844939727
finished creating graph Tehran1292514023
finished creating graph Tehran4640003489
finished creating graph Tehran5243833774
finished creating graph Istanbul1058892495
finished creating graph Istanbul1134770756
finished creating graph Istanbul775654779
finished creating graph Istanbul12162557816
finished creating graph Istanbul2261051761
finished creating graph Mogadishu1412578845
finished creating graph Mogadishu2429173550
finished creating graph Mogadishu317671002
finished creating graph Mogadishu12726434014
finished creating graph Mogadishu5636439912
finished creating graph Bangkok2629986341
finished creating graph Bangkok3825321129
finished creating graph Bangkok1687458454
finished creating graph Bangkok7936842527
finished creating graph Bangkok4822918883
finished creating graph Melbourne319642519
finished creating graph Melbourne683089001
finished creating graph Melbourne247492201
finished creating graph Melbourne3353364995
finished creating graph Melbourne9976415226
finished creating graph Shanghai622623197
finished creating graph Shanghai838507201
finished creating graph Shanghai475861592
finished creating graph Shanghai11751956757
finished creating graph Shanghai1803562530
finished

In [12]:
# The next step is to add weights to the edges of the graph.
import pandas as pd # for reading the csv file
import joblib # replacing multiprocessing with joblib
df = pd.read_csv(city_sample_nodes_path)

def add_graph_weights(row):
    og = rna.origin_graph.from_graphml(graphml_path=row['graph_path'])
    og.add_simplest_paths_from_origin()
    og.add_weights('deviation_from_prototypical')
    og.add_weights('node_degree')
    og.add_weights('instruction_equivalent')
    #og.add_weights('betweenness_centrality')
    og.save_graph(row['graph_path'])
    print(f"Finished with graph: {row['city_name_en']} node: {row['node_id']}",flush=True)
    return True, row['city_name_en'], row['node_id']

# Number of processes to use
#num_processes = (joblib.cpu_count()-2)
#print(f"Number of processes to use: {num_processes}")
# Collect results from joblib
rows_to_process = []
for idx, row in df.iterrows():
    if row['weight_added'] == True:
        results.append(add_graph_weights(row))
    #rows_to_process.append(row)


#results = joblib.Parallel(n_jobs=num_processes, backend='loky')(
#    joblib.delayed(add_graph_weights)(row) for row in rows_to_process
#)


for result in results:
    if result[0]:
        mask = (df['city_name_en'] == result[1]) & (df['node_id'] == result[2])
        df.loc[mask, 'weights_added'] = True
df.to_csv(city_sample_nodes_path)

Finished with graph: Lima node: 1330495156
Finished with graph: Lima node: 1359116964
Finished with graph: Lima node: 848394908
Finished with graph: Lima node: 11050450864
Finished with graph: Lima node: 3107812023
Finished with graph: Buenos Aires node: 1406097496
Finished with graph: Buenos Aires node: 1422501545
Finished with graph: Buenos Aires node: 1357237840
Finished with graph: Buenos Aires node: 5533758329
Finished with graph: Buenos Aires node: 9852258020
Finished with graph: Mexico City node: 506391266
Finished with graph: Mexico City node: 762649538
Finished with graph: Mexico City node: 280151390
Finished with graph: Mexico City node: 7951676238
Finished with graph: Mexico City node: 2335775204
Finished with graph: Miami node: 99232717
Finished with graph: Miami node: 99343234
Finished with graph: Miami node: 99119377
Finished with graph: Miami node: 3505119075
Finished with graph: Miami node: 8073291354
Finished with graph: Pittsburgh node: 105097688
Finished with graph: Pittsburgh node: 105719059
Finished with graph: Pittsburgh node: 104716142
Finished with graph: Pittsburgh node: 106075671
Finished with graph: Pittsburgh node: 1027077885
Finished with graph: Seattle node: 53199898
Finished with graph: Seattle node: 59594019
Finished with graph: Seattle node: 53113626
Finished with graph: Seattle node: 4607144987
Finished with graph: Seattle node: 9179103065
Finished with graph: Rome node: 298573501
Finished with graph: Rome node: 302024499
Finished with graph: Rome node: 259041554
Finished with graph: Rome node: 5368981033
Finished with graph: Rome node: 307509211
Finished with graph: Barcelona node: 600061492
Finished with graph: Barcelona node: 1017920257
Finished with graph: Barcelona node: 269381939
Finished with graph: Barcelona node: 1883289262
Finished with graph: Barcelona node: 4111508831
Finished with graph: Stockholm node: 299803577
Finished with graph: Stockholm node: 447281012
Finished with graph: Stockholm node: 34032590
Finished with graph: Stockholm node: 1251168984
Finished with graph: Stockholm node: 1976750065
Finished with graph: Tehran node: 2090004410
Finished with graph: Tehran node: 3844939727
Finished with graph: Tehran node: 1292514023
Finished with graph: Tehran node: 4640003489
Finished with graph: Tehran node: 5243833774
Finished with graph: Istanbul node: 1058892495
Finished with graph: Istanbul node: 1134770756
Finished with graph: Istanbul node: 775654779
Finished with graph: Istanbul node: 12162557816
Finished with graph: Istanbul node: 2261051761
Finished with graph: Mogadishu node: 1412578845
Finished with graph: Mogadishu node: 2429173550
Finished with graph: Mogadishu node: 317671002
Finished with graph: Mogadishu node: 12726434014
Finished with graph: Mogadishu node: 5636439912
Finished with graph: Bangkok node: 2629986341
Finished with graph: Bangkok node: 3825321129
Finished with graph: Bangkok node: 1687458454
Finished with graph: Bangkok node: 7936842527
Finished with graph: Bangkok node: 4822918883
Finished with graph: Melbourne node: 319642519
Finished with graph: Melbourne node: 683089001
Finished with graph: Melbourne node: 247492201
Finished with graph: Melbourne node: 3353364995
Finished with graph: Melbourne node: 9976415226
Finished with graph: Shanghai node: 622623197
Finished with graph: Shanghai node: 838507201
Finished with graph: Shanghai node: 475861592
Finished with graph: Shanghai node: 11751956757
Finished with graph: Shanghai node: 1803562530

In [ ]:
import pandas as pd # for reading the csv file
import joblib # replacing multiprocessing with joblib
import route_network_analysis as rna

df = pd.read_csv(city_sample_nodes_path)
display(df)
local_odpair_folder = os.path.join(base_path, "od_pair_data")
local_odpair_base_folder = os.path.join(local_odpair_folder, 'base')
local_odpair_geom_folder = os.path.join(local_odpair_folder, 'geom')
print(f"odpair data will be stored at {local_odpair_folder}")
os.makedirs(local_odpair_folder, exist_ok=True)
os.makedirs(local_odpair_base_folder, exist_ok=True)
os.makedirs(local_odpair_geom_folder, exist_ok=True)


df['od_pairs_added'] = False


def get_od_pairs(row):
    print(f"Finding OD_pairs for graph: {row['city_name_en']} node: {row['node_id']}",flush=True)
    og = rna.origin_graph.from_graphml(graphml_path=row['graph_path'])
    og.create_od_pairs(min_radius=min_od_distance, max_radius=max_od_distance, sample_size=od_pair_sample_size)
    od_pair_data = og.get_od_pair_data()
    od_pair_geom_data = og.get_od_pair_geom_data()
    json_base_path = os.path.join(local_odpair_base_folder, f"od_pair_{row['city_name_en']}_{row['node_id']}.json")
    json_geom_path = os.path.join(local_odpair_geom_folder, f"od_pair_geom_{row['city_name_en']}_{row['node_id']}.json")
    od_pair_data.to_json(json_base_path, orient="records", default_handler=str, indent=2)
    od_pair_geom_data.to_json(json_geom_path, orient="records", default_handler=str, indent=2)
    print(f"Finished finding OD_pairs for graph: {row['city_name_en']} node: {row['node_id']}",flush=True)
    return True,row['city_name_en'],row['node_id']


num_processes = (joblib.cpu_count() - 4)
print(f"Number of processes to use: {num_processes}")



rows_to_process = []
for idx, row in df.iterrows():
    #if not row['od_pairs_added']:
        rows_to_process.append(row)

results = joblib.Parallel(n_jobs=num_processes, backend='loky')(
    joblib.delayed(get_od_pairs)(row) for row in rows_to_process
)

for result in results:
    if result[0]:
        mask = (df['city_name_en'] == result[1]) & (df['node_id'] == result[2])
        df.loc[mask, 'od_pairs_added'] = True


import glob

# Get all json files from od_pair_data folder
od_pair_base_files = glob.glob(os.path.join(local_odpair_base_folder, "*.json"))
od_pair_geom_files = glob.glob(os.path.join(local_odpair_geom_folder, "*.json"))
# Read and combine all json files
od_pair_base_data = pd.concat([pd.read_json(f) for f in od_pair_base_files], ignore_index=False)
od_pair_geom_data = pd.concat([pd.read_json(f) for f in od_pair_geom_files], ignore_index=False)

print(f"Total number of od-pairs: {len(od_pair_base_data)}")
print(od_pair_base_data.columns)


# The od-pair data contains lists and dictionaries that are not easily saved to a csv file, so we store it as a json file.
# Still, there some columns that need to be serialized to strings such as shapely polygon objects.



od_pair_data_geom_path_json = os.path.join(local_odpair_folder, 'origin_od_pair_geom.json')
od_pair_data_base_path_csv = os.path.join(local_odpair_folder, 'origin_od_pair_base.csv')

od_pair_base_data.to_csv(od_pair_data_base_path_csv)
od_pair_geom_data.to_json(od_pair_data_geom_path_json, orient="records", default_handler=str, indent=2)

print("done")

,Unnamed: 0.1,Unnamed: 0,city_name,city_name_en,country_name,country_name_en,continent,region,network_type,node_id,node_latlon,graph_path,weights_added
0,0,0,Lima,Lima,Perú,Peru,South America,Latin America,drive,1330495156,"(-11.9789855, -77.0547884)",/media/arvidkh/projekt/streetnetwork-alignment...,True
1,1,1,Lima,Lima,Perú,Peru,South America,Latin America,drive,1359116964,"(-12.0097364, -77.0931582)",/media/arvidkh/projekt/streetnetwork-alignment...,True
2,2,2,Lima,Lima,Perú,Peru,South America,Latin America,drive,848394908,"(-12.0276739, -77.0958306)",/media/arvidkh/projekt/streetnetwork-alignment...,True
3,3,3,Lima,Lima,Perú,Peru,South America,Latin America,drive,11050450864,"(-11.9433227, -77.0076102)",/media/arvidkh/projekt/streetnetwork-alignment...,True
4,4,4,Lima,Lima,Perú,Peru,South America,Latin America,drive,3107812023,"(-11.8927561, -76.9439907)",/media/arvidkh/projekt/streetnetwork-alignment...,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,70,70,Shanghai,Shanghai,中国,China,Asia,Asia/Oceania,drive,622623197,"(31.2047956, 121.4662599)",/media/arvidkh/projekt/streetnetwork-alignment...,True
71,71,71,Shanghai,Shanghai,中国,China,Asia,Asia/Oceania,drive,838507201,"(31.1842744, 121.3899739)",/media/arvidkh/projekt/streetnetwork-alignment...,True
72,72,72,Shanghai,Shanghai,中国,China,Asia,Asia/Oceania,drive,475861592,"(31.2502287, 121.4892488)",/media/arvidkh/projekt/streetnetwork-alignment...,True
73,73,73,Shanghai,Shanghai,中国,China,Asia,Asia/Oceania,drive,11751956757,"(31.21574, 121.3964503)",/media/arvidkh/projekt/streetnetwork-alignment...,True
74,74,74,Shanghai,Shanghai,中国,China,Asia,Asia/Oceania,drive,1803562530,"(31.2181653, 121.5274726)",/media/arvidkh/projekt/streetnetwork-alignment...,True

odpair data will be stored at /media/arvidkh/projekt/streetnetwork-alignment/2025-11-illustration/od_pair_data
Number of processes to use: 4

In [ ]:
import pandas as pd # for reading the csv file
import joblib # replacing multiprocessing with joblib
import route_network_analysis as rna

df = pd.read_csv(city_sample_nodes_path)
display(df)
local_odpair_folder = os.path.join(base_path, "od_pair_data")
local_odpair_base_folder = os.path.join(local_odpair_folder, 'base')
local_odpair_geom_folder = os.path.join(local_odpair_folder, 'geom')
print(f"odpair data will be stored at {local_odpair_folder}")
os.makedirs(local_odpair_folder, exist_ok=True)
os.makedirs(local_odpair_base_folder, exist_ok=True)
os.makedirs(local_odpair_geom_folder, exist_ok=True)


df['od_pairs_added'] = False


def get_od_pairs(row):
    print(f"Finding OD_pairs for graph: {row['city_name_en']} node: {row['node_id']}",flush=True)
    og = rna.origin_graph.from_graphml(graphml_path=row['graph_path'])
    og.create_od_pairs(min_radius=min_od_distance, max_radius=max_od_distance, sample_size=od_pair_sample_size)
    od_pair_data = og.get_od_pair_data()
    od_pair_geom_data = og.get_od_pair_geom_data()
    json_base_path = os.path.join(local_odpair_base_folder, f"od_pair_{row['city_name_en']}_{row['node_id']}.json")
    json_geom_path = os.path.join(local_odpair_geom_folder, f"od_pair_geom_{row['city_name_en']}_{row['node_id']}.json")
    od_pair_data.to_json(json_base_path, orient="records", default_handler=str, indent=2)
    od_pair_geom_data.to_json(json_geom_path, orient="records", default_handler=str, indent=2)
    print(f"Finished finding OD_pairs for graph: {row['city_name_en']} node: {row['node_id']}",flush=True)
    return True,row['city_name_en'],row['node_id']


num_processes = (joblib.cpu_count() - 4)
print(f"Number of processes to use: {num_processes}")



rows_to_process = []
for idx, row in df.iterrows():
        json_base_path = os.path.join(local_odpair_base_folder, f"od_pair_{row['city_name_en']}_{row['node_id']}.json")
        if not os.path.exists(json_base_path):
            rows_to_process.append(row)

results = joblib.Parallel(n_jobs=num_processes, backend='loky')(
    joblib.delayed(get_od_pairs)(row) for row in rows_to_process
)

for result in results:
    if result[0]:
        mask = (df['city_name_en'] == result[1]) & (df['node_id'] == result[2])
        df.loc[mask, 'od_pairs_added'] = True


import glob


# Get all json files from od_pair_data folder
od_pair_base_files = glob.glob(os.path.join(local_odpair_base_folder, "*.json"))
od_pair_geom_files = glob.glob(os.path.join(local_odpair_geom_folder, "*.json"))
# Read and combine all json files
od_pair_base_data = pd.concat([pd.read_json(f) for f in od_pair_base_files], ignore_index=False)
od_pair_geom_data = pd.concat([pd.read_json(f) for f in od_pair_geom_files], ignore_index=False)

print(f"Total number of od-pairs: {len(od_pair_base_data)}")
print(od_pair_base_data.columns)


# The od-pair data contains lists and dictionaries that are not easily saved to a csv file, so we store it as a json file.
# Still, there some columns that need to be serialized to strings such as shapely polygon objects.



od_pair_data_geom_path_json = os.path.join(local_odpair_folder, 'origin_od_pair_geom.json')
od_pair_data_base_path_csv = os.path.join(local_odpair_folder, 'origin_od_pair_base.csv')

od_pair_base_data.to_csv(od_pair_data_base_path_csv)
od_pair_geom_data.to_json(od_pair_data_geom_path_json, orient="records", default_handler=str, indent=2)

print("done")

In [2]:
import pandas as pd
import os
import glob

# Assuming base_path and city_sample_nodes_path are defined
df = pd.read_csv(city_sample_nodes_path)
display(df)

local_odpair_folder = os.path.join(base_path, "od_pair_data")
local_odpair_base_folder = os.path.join(local_odpair_folder, 'base')
local_odpair_geom_folder = os.path.join(local_odpair_folder, 'geom')
local_odpair_bearings_folder = os.path.join(local_odpair_folder, 'bearings')

print(f"odpair data will be stored at {local_odpair_folder}")
os.makedirs(local_odpair_folder, exist_ok=True)
os.makedirs(local_odpair_base_folder, exist_ok=True)
os.makedirs(local_odpair_geom_folder, exist_ok=True)
os.makedirs(local_odpair_bearings_folder, exist_ok=True)

# Get all json files from od_pair_data folder
od_pair_base_files = glob.glob(os.path.join(local_odpair_base_folder, "*.json"))
od_pair_geom_files = glob.glob(os.path.join(local_odpair_geom_folder, "*.json"))
od_pair_bearings_files = glob.glob(os.path.join(local_odpair_bearings_folder, "*.json"))

# Define bearing columns
bearing_columns = [
    "bearings_undirected",
    "bearings_undirected_weights",
    "bearings_directed",
    "bearings_directed_weights",
    "bearings_od_fwd",
    "bearings_od_bwd",
    "bearings_od_perp_fwd",
    "bearings_od_perp_bwd"
]

# Process each base JSON file to separate bearing data
for f in od_pair_base_files:
    data = pd.read_json(f)
    bearings_data = data[['id'] + bearing_columns]
    data.drop(columns=bearing_columns, inplace=True)

    # Save the processed base data back to the base folder
    base_filename = os.path.basename(f)
    data.to_json(os.path.join(local_odpair_base_folder, base_filename), orient="records", indent=2)

    # Save the bearings data to the bearings folder
    bearings_filename = base_filename.replace('.json', '_bearings.json')
    bearings_data.to_json(os.path.join(local_odpair_bearings_folder, bearings_filename), orient="records", indent=2)

# Concatenate geom data
#od_pair_geom_data = pd.concat([pd.read_json(f) for f in od_pair_geom_files], ignore_index=False)

print("Processing complete")

# Save the concatenated geom data
#od_pair_data_geom_path_json = os.path.join(local_odpair_folder, 'origin_od_pair_geom.json')
#od_pair_geom_data.to_json(od_pair_data_geom_path_json, orient="records", default_handler=str, indent=2)

print("done")

,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,city_name,city_name_en,country_name,country_name_en,continent,region,network_type,node_id,node_latlon,graph_path,weights_added,od_pairs_added
0,0,0,0,0,0,0,0,0,Bangkok,Bangkok,ประเทศไทย,Thailand,Asia,Asia/Oceania,drive,2733298223,"(13.7253693, 100.4953615)",/proj/nobackup/streetnetwork-alignment/2025-04...,True,True
1,1,1,1,1,1,1,1,1,Bangkok,Bangkok,ประเทศไทย,Thailand,Asia,Asia/Oceania,drive,3825324563,"(13.7843515, 100.4392777)",/proj/nobackup/streetnetwork-alignment/2025-04...,True,True
2,2,2,2,2,2,2,2,2,Bangkok,Bangkok,ประเทศไทย,Thailand,Asia,Asia/Oceania,drive,1687458348,"(13.7918891, 100.5686954)",/proj/nobackup/streetnetwork-alignment/2025-04...,True,True
3,3,3,3,3,3,3,3,3,Bangkok,Bangkok,ประเทศไทย,Thailand,Asia,Asia/Oceania,drive,7926838114,"(13.7020039, 100.5380657)",/proj/nobackup/streetnetwork-alignment/2025-04...,True,True
4,4,4,4,4,4,4,4,4,Bangkok,Bangkok,ประเทศไทย,Thailand,Asia,Asia/Oceania,drive,4772368452,"(13.668279, 100.4044342)",/proj/nobackup/streetnetwork-alignment/2025-04...,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,495,495,495,495,495,495,495,Washington,Washington,United States,United States,North America,US/Canada,drive,49896757,"(38.9773557, -77.0191765)",/proj/nobackup/streetnetwork-alignment/2025-04...,True,True
496,496,496,496,496,496,496,496,496,Washington,Washington,United States,United States,North America,US/Canada,drive,50654959,"(38.8068877, -76.9933723)",/proj/nobackup/streetnetwork-alignment/2025-04...,True,True
497,497,497,497,497,497,497,497,497,Washington,Washington,United States,United States,North America,US/Canada,drive,49761428,"(38.885008, -76.928403)",/proj/nobackup/streetnetwork-alignment/2025-04...,True,True
498,498,498,498,498,498,498,498,498,Washington,Washington,United States,United States,North America,US/Canada,drive,11368228087,"(38.856723, -76.9699374)",/proj/nobackup/streetnetwork-alignment/2025-04...,True,True
499,499,499,499,499,499,499,499,499,Washington,Washington,United States,United States,North America,US/Canada,drive,63352404,"(38.8751037, -77.1276724)",/proj/nobackup/streetnetwork-alignment/2025-04...,True,True

odpair data will be stored at /proj/nobackup/streetnetwork-alignment/2025-04-full_dataset/od_pair_data
Processing complete
done

In [ ]:
import pandas as pd
import os
import glob
import numpy as np

# Assuming base_path and city_sample_nodes_path are defined
df = pd.read_csv(city_sample_nodes_path)
display(df)

local_odpair_folder = os.path.join(base_path, "od_pair_data")
local_odpair_base_folder = os.path.join(local_odpair_folder, 'base')
local_odpair_geom_folder = os.path.join(local_odpair_folder, 'geom')
local_odpair_bearings_folder = os.path.join(local_odpair_folder, 'bearings')

print(f"odpair data will be stored at {local_odpair_folder}")
os.makedirs(local_odpair_folder, exist_ok=True)
os.makedirs(local_odpair_base_folder, exist_ok=True)
os.makedirs(local_odpair_geom_folder, exist_ok=True)
os.makedirs(local_odpair_bearings_folder, exist_ok=True)

# Get all json files from od_pair_data folder

# 1. Gather all bearings JSON files
od_pair_bearings_files = glob.glob(os.path.join(local_odpair_bearings_folder, "*.json"))

# 2. Determine chunk sizes for splitting files into three groups
num_files = len(od_pair_bearings_files)
chunk_indices = np.array_split(np.arange(num_files), 3)

# 3. For each chunk, load only those files, concatenate, and save as a separate file
od_pair_bearings_chunk_paths = []
for i, indices in enumerate(chunk_indices):
    chunk_files = [od_pair_bearings_files[j] for j in indices]
    chunk_df = pd.concat([pd.read_json(f) for f in chunk_files], ignore_index=False)
    chunk_path = os.path.join(local_odpair_bearings_folder, f"od_pair_bearings_chunk_{i+1}.csv")
    chunk_df.to_csv(chunk_path)
    od_pair_bearings_chunk_paths.append(chunk_path)

# Optionally, load the three chunks as DataFrames (one at a time, if needed)
# od_pair_bearings_chunk1 = pd.read_csv(od_pair_bearings_chunk_paths[0])
# od_pair_bearings_chunk2 = pd.read_csv(od_pair_bearings_chunk_paths[1])
# od_pair_bearings_chunk3 = pd.read_csv(od_pair_bearings_chunk_paths[2])


od_pair_base_files = glob.glob(os.path.join(local_odpair_base_folder, "*.json"))
od_pair_base_data = pd.concat([pd.read_json(f) for f in od_pair_base_files], ignore_index=False)
od_pair_base_data.to_csv(od_pair_data_base_path_csv)


od_pair_geom_files = glob.glob(os.path.join(local_odpair_geom_folder, "*.json"))
od_pair_geom_data = pd.concat([pd.read_json(f) for f in od_pair_geom_files], ignore_index=False)
od_pair_geom_data.to_json(od_pair_data_geom_path_json, orient="records", default_handler=str, indent=2)


#od_pair_bearings_data.to_csv(od_pair_data_bearings_path_csv)
# Save the concatenated geom data
#od_pair_base_data.to_csv(od_pair_data_base_path_csv)
#od_pair_bearings_data.to_csv(od_pair_data_bearings_path_csv)
#od_pair_geom_data.to_json(od_pair_data_geom_path_json, orient="records", default_handler=str, indent=2)

print("done")

,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,city_name,city_name_en,country_name,country_name_en,continent,region,network_type,node_id,node_latlon,graph_path,weights_added,od_pairs_added
0,0,0,0,0,0,0,0,0,Bangkok,Bangkok,ประเทศไทย,Thailand,Asia,Asia/Oceania,drive,2733298223,"(13.7253693, 100.4953615)",/proj/nobackup/streetnetwork-alignment/2025-04...,True,True
1,1,1,1,1,1,1,1,1,Bangkok,Bangkok,ประเทศไทย,Thailand,Asia,Asia/Oceania,drive,3825324563,"(13.7843515, 100.4392777)",/proj/nobackup/streetnetwork-alignment/2025-04...,True,True
2,2,2,2,2,2,2,2,2,Bangkok,Bangkok,ประเทศไทย,Thailand,Asia,Asia/Oceania,drive,1687458348,"(13.7918891, 100.5686954)",/proj/nobackup/streetnetwork-alignment/2025-04...,True,True
3,3,3,3,3,3,3,3,3,Bangkok,Bangkok,ประเทศไทย,Thailand,Asia,Asia/Oceania,drive,7926838114,"(13.7020039, 100.5380657)",/proj/nobackup/streetnetwork-alignment/2025-04...,True,True
4,4,4,4,4,4,4,4,4,Bangkok,Bangkok,ประเทศไทย,Thailand,Asia,Asia/Oceania,drive,4772368452,"(13.668279, 100.4044342)",/proj/nobackup/streetnetwork-alignment/2025-04...,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,495,495,495,495,495,495,495,Washington,Washington,United States,United States,North America,US/Canada,drive,49896757,"(38.9773557, -77.0191765)",/proj/nobackup/streetnetwork-alignment/2025-04...,True,True
496,496,496,496,496,496,496,496,496,Washington,Washington,United States,United States,North America,US/Canada,drive,50654959,"(38.8068877, -76.9933723)",/proj/nobackup/streetnetwork-alignment/2025-04...,True,True
497,497,497,497,497,497,497,497,497,Washington,Washington,United States,United States,North America,US/Canada,drive,49761428,"(38.885008, -76.928403)",/proj/nobackup/streetnetwork-alignment/2025-04...,True,True
498,498,498,498,498,498,498,498,498,Washington,Washington,United States,United States,North America,US/Canada,drive,11368228087,"(38.856723, -76.9699374)",/proj/nobackup/streetnetwork-alignment/2025-04...,True,True
499,499,499,499,499,499,499,499,499,Washington,Washington,United States,United States,North America,US/Canada,drive,63352404,"(38.8751037, -77.1276724)",/proj/nobackup/streetnetwork-alignment/2025-04...,True,True

odpair data will be stored at /proj/nobackup/streetnetwork-alignment/2025-04-full_dataset/od_pair_data

In [10]:
print(od_pair_base_data['bearings_undirected'])

KeyError: 'bearings_undirected'